### PR TITLE
Address Install Failures

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Review by martindurant — APPROVED** [review]
Obviously the upstream cold is now rather old, but if this is still useful for someone, I'm happy for builds to continue to be made. As far as I can tell, this PR is fine.

**Comment by rxm7706** [comment]
> Obviously the upstream cold is now rather old, but if this is still useful for someone, I'm happy for builds to continue to be made. As far as I can tell, this PR is fine.

Thanks @martindurant 

Could you Please review and merge - Also just to make sure you noticed - I removed  - setuptools from host. 

FYI - This is the error I was getting, while playing around with intake-avro - Likely that will require one more PR to make the package work with poetry too. But this PR should make the conda package upto date. 

`Note: This error originates from the build backend, and is likely not a problem with poetry but with uavro (0.1.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "uavro (==0.1.2)"'.`

**Comment by martindurant** [comment]
I daresay that the build stuff in the repo can be updated, perhaps all the way to pyproject.toml .

**Pull request merged**
